<!doctype html>
<html lang="fa" dir="rtl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>تحویل‌های انبار</title><style>body{font-family:Tahoma,"Segoe UI",sans-serif;background:#f5f7fb;color:#172033;margin:0;padding:28px}main{max-width:1100px;margin:auto;background:#fff;border:1px solid #e5eaf0;border-radius:14px;padding:22px}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #e5eaf0;text-align:right}button{border:0;border-radius:7px;padding:8px 12px;cursor:pointer;color:#fff}.approve{background:#087f23}.reject{background:#b42318}.pending{color:#a16207}.approved{color:#087f23}.rejected{color:#b42318}.actions{display:flex;gap:7px}.note{width:130px;padding:7px;border:1px solid #cbd5e1;border-radius:7px}</style></head>
<body><main><h1>تحویل به فروشگاه / افزایش موجودی انبار</h1><table><tr><th>کاربر</th><th>دارایی</th><th>واحد</th><th>مقدار</th><th>وضعیت</th><th>اقدام</th></tr>
@php($assets=['gold'=>'طلا','silver_995'=>'نقره ۹۹۵','silver_9999'=>'نقره ۹۹۹٫۹','full_coin'=>'تمام سکه','half_coin'=>'نیم سکه','quarter_coin'=>'ربع سکه'])
@php($units=['gram'=>'گرم','mesghal'=>'مثقال','count'=>'تعداد'])
@forelse($deliveries as $delivery)<tr><td>{{ $delivery->user->name }}</td><td>{{ $assets[$delivery->asset] ?? $delivery->asset }}</td><td>{{ $units[$delivery->unit] ?? $delivery->unit }}</td><td>{{ $delivery->quantity }}</td><td class="{{ $delivery->status }}">{{ ['pending'=>'در انتظار بررسی','approved'=>'تأیید شده','rejected'=>'رد شده'][$delivery->status] }}</td><td>@if($delivery->status === 'pending')<div class="actions"><form class="review-form" method="post" action="{{ route('admin.inventory-deliveries.approve',$delivery) }}">@csrf<input class="note" name="note" placeholder="یادداشت اختیاری"><button class="approve">تأیید</button></form><form class="review-form" method="post" action="{{ route('admin.inventory-deliveries.reject',$delivery) }}">@csrf<input class="note" name="note" placeholder="دلیل رد"><button class="reject">رد</button></form></div>@endif</td></tr>
@empty<tr><td colspan="6">درخواستی برای بررسی وجود ندارد.</td></tr>@endforelse
</table></main><script>document.querySelectorAll('.review-form').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(response.ok)location.reload();else alert((await response.json().catch(()=>({}))).message||'ثبت نتیجه ناموفق بود.')}));</script></body></html>
