<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('users', function(Blueprint $t){$t->string('telegram_chat_id')->nullable()->unique();$t->decimal('wallet_balance',18,0)->default(0);$t->boolean('is_admin')->default(false);});
 Schema::create('price_snapshots', function(Blueprint $t){$t->id();$t->string('symbol')->index();$t->string('title');$t->decimal('price',18,0);$t->timestamp('source_updated_at')->nullable();$t->timestamps();});
 Schema::create('trades', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->enum('side',['buy','sell']);$t->enum('unit',['mesghal','gram']);$t->decimal('quantity',12,3);$t->decimal('unit_price',18,0);$t->decimal('total_price',18,0);$t->string('price_symbol');$t->enum('status',['submitted','accepted','rejected'])->default('submitted');$t->string('talaboard_reference')->nullable();$t->timestamp('traded_at');$t->timestamps();$t->index(['side','traded_at']);});
 Schema::create('deposit_requests', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->decimal('amount',18,0);$t->string('receipt_path');$t->enum('status',['pending','approved','rejected'])->default('pending');$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->text('admin_note')->nullable();$t->timestamps();});
 Schema::create('wallet_transactions', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->decimal('amount',18,0);$t->string('type');$t->string('reference_type')->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->string('description')->nullable();$t->timestamps();});
 } public function down(): void {Schema::dropIfExists('wallet_transactions');Schema::dropIfExists('deposit_requests');Schema::dropIfExists('trades');Schema::dropIfExists('price_snapshots');Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['telegram_chat_id','wallet_balance','is_admin']));} };
